script(python): change in python versions possible now
* also bump python to 3.11.0

diff --git a/home/.chezmoiscripts/linux/run_onchange_after_81_install-python.sh.tmpl b/home/.chezmoiscripts/linux/run_onchange_after_81_install-python.sh.tmpl
--- a/home/.chezmoiscripts/linux/run_onchange_after_81_install-python.sh.tmpl
+++ b/home/.chezmoiscripts/linux/run_onchange_after_81_install-python.sh.tmpl
@@ -1,37 +1,56 @@
 #!/usr/bin/env bash
+# vim: set expandtab ts=4 sw=4 ft=sh:
+
 set -euo pipefail
 
-# TODO: this installation just check if .pyenv directory present or not but
-# underlying python version might be old. Need python version validation
-if [ ! -d $HOME/.pyenv ];
-then
-    echo "install pyenv"
-    unset PYENV_ROOT
-    curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
+# expected python version
+PYTHON_VERSION={{ .pythonVersion }}
 
-    echo "setup python"
-    # vars
-    PYTHON_VERSION={{ .pythonVersion }}
-    PYENV_ROOT="$HOME/.pyenv"
-    PATH="$PYENV_ROOT/bin:$PATH"
-    eval "$(pyenv init --path)"
-    pyenv install $PYTHON_VERSION || true
-    # set global python version
-    pyenv global $PYTHON_VERSION
+#######################################
+# Install pyenv
+#######################################
+install_pyenv() {
+	echo "*** Installing pyenv ***"
+	unset PYENV_ROOT
+	curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
+}
+
+#######################################
+# Install python with help of pyenv
+#######################################
+install_python() {
+	echo "*** Setting up Python {{ .pythonVersion }} *** "
+	PYENV_ROOT="$HOME/.pyenv"
+	PATH="$PYENV_ROOT/bin:$PATH"
+	eval "$(pyenv init --path)"
+	pyenv install $PYTHON_VERSION || true
+	# set global python version
+	pyenv global $PYTHON_VERSION
+}
+
+# Setup pyenv
+if [ ! "$(command -v pyenv &>/dev/null)" ]; then
+	pyenv update
+else
+	# pyenv setup required
+	install_pyenv
+fi
+
+# lets see if I need python version change!
+CURRENT_VERSION="$(pyenv versions | grep "set by" | awk '{ print $2 }')"
+if [ "$CURRENT_VERSION" != "$PYTHON_VERSION" ]; then
+	echo "*** Python update required ***"
+	[ "$CURRENT_VERSION" != "system" ] && pyenv uninstall -f "$CURRENT_VERSION"
+	install_python
+
+	# NOTE: removal of python breaks poetry, so re-installation required
+	echo "Cleaning up Old Poetry..."
+	curl -sSL https://install.python-poetry.org | python3 - --uninstall
 fi
 
 # some python packages setup
-echo "Installing python packages"
+echo "*** Installing python packages ***"
 pip install -U pip pipenv black mypy pylint isort
-
-# deal with old poetry clean up
-# Poetry 1.1 series releases are not able to update in-place to 1.2 or newer series 
-# releases. To migrate to newer releases, uninstall using your original install method,
-# and then reinstall using the methods above.
-if poetry --version | grep -q "1.1"; then
-  echo "Cleaning up Old Poetry..."
-  curl -sSL https://install.python-poetry.org | python3 - --uninstall
-fi
 
 # poetry installtion
 curl -sSL https://install.python-poetry.org | python3 -
