script: using rg with sf

diff --git a/home/private_dot_local/private_bin/executable_sf b/home/private_dot_local/private_bin/executable_sf
--- a/home/private_dot_local/private_bin/executable_sf
+++ b/home/private_dot_local/private_bin/executable_sf
@@ -2,13 +2,18 @@
 # supercharded SSH with fzf and ripgrep.
 # scavange SSH config with ripgrep and present with fzf and login to selected hostname
 
+if [ ! -x "$(command -v rg)" ]; then
+  echo "Error: rg is not installed." >&2
+  exit 1
+fi
+
 if [ ! -f ~/.ssh/config ]; then
   echo "no ssh config file found"
   exit 1
 fi
 
 # reference: https://www.jamesridgway.co.uk/list-ssh-hosts-from-your-ssh-config/
-data=$(grep -P "^Host ([^*]+)$" $HOME/.ssh/config | sed 's/Host //')
+data=$(rg -P "^Host ([^*]+)$" $HOME/.ssh/config | sed 's/Host //')
 
 selected=$(echo "$data" | fzf)
 
